version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install apt-transport-https ca-certificates curl software-properties-common
      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - apt-get update
      - apt-get -y install docker-ce # Install Docker

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 239302956728.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t backpack-web .

  post_build:
    commands:
      - echo Building Docker images, pushing to Docker Hub, etc.
      - docker tag backpack-web:latest 239302956728.dkr.ecr.us-east-1.amazonaws.com/backpack-web:latest
      - docker push 239302956728.dkr.ecr.us-east-1.amazonaws.com/backpack-web:latest
